name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Replace secrets in index.html
        run: |
          # index.html에 있는 "$BDB_..."를 찾아서 
          # GitHub Secrets의 "BDB_..._PLACEHOLDER" 값으로 바꿉니다.
          
          sed -i "s|\$BDB_API_KEY|${{ secrets.BDB_API_KEY_PLACEHOLDER }}|g" index.html
          sed -i "s|\$BDB_AUTH_DOMAIN|${{ secrets.BDB_AUTH_DOMAIN_PLACEHOLDER }}|g" index.html
          sed -i "s|\$BDB_PROJECT_ID|${{ secrets.BDB_PROJECT_ID_PLACEHOLDER }}|g" index.html
          sed -i "s|\$BDB_STORAGE_BUCKET|${{ secrets.BDB_STORAGE_BUCKET_PLACEHOLDER }}|g" index.html
          sed -i "s|\$BDB_SENDER_ID|${{ secrets.BDB_SENDER_ID_PLACEHOLDER }}|g" index.html
          sed -i "s|\$BDB_APP_ID|${{ secrets.BDB_APP_ID_PLACEHOLDER }}|g" index.html

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          branch: gh-pages
          clean: true
