name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Replace secrets and Deploy
        run: |
          # 1. 금고에서 값을 가져와 임시 환경 변수로 설정합니다.
          export BDB_API_KEY="${{ secrets.BDB_API_KEY_PLACEHOLDER }}"
          export BDB_AUTH_DOMAIN="${{ secrets.BDB_AUTH_DOMAIN_PLACEHOLDER }}"
          export BDB_PROJECT_ID="${{ secrets.BDB_PROJECT_ID_PLACEHOLDER }}"
          export BDB_STORAGE_BUCKET="${{ secrets.BDB_STORAGE_BUCKET_PLACEHOLDER }}"
          export BDB_SENDER_ID="${{ secrets.BDB_SENDER_ID_PLACEHOLDER }}"
          export BDB_APP_ID="${{ secrets.BDB_APP_ID_PLACEHOLDER }}"

          # 2. envsubst 명령어로 index.html 내의 $변수들을 실제 값으로 치환합니다.
          # (임시 파일에 저장했다가 다시 덮어씁니다)
          envsubst < index.html > index.tmp && mv index.tmp index.html

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          branch: gh-pages
